---
title: "Projects"
description: |
  A repository of my analytics projects
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


```{r, include=FALSE}
library(htmltools)
source("R/create_proj_card.R")
```



```{r}

create_proj_card(
  img_src = "images/fred-logo.svg",
  url = "https://steodose.github.io/macro-trends/",
  title = "Macro Pulse",
  text = "Website dedicated to economic and financial analysis using data provided by the Federal Reserve Economic Database (FRED).",
  text2 = NULL
)



create_proj_card(
  img_src = "images/NHL.png",
  url = "https://steodose.github.io/nhl-dashboard/#teams",
  title = "NHL Analytics",
  text = "NHL analytics web app showing the latest standings, advanced stats and Stanley Cup odds for all 32 NHL teams.",
  text2 = NULL
)


create_proj_card(
  img_src = "images/MLB Grouped.png",
  url = "https://steodose.github.io/MLB/MLB-Summary.html",
  title = "MLB Analytics",
  text = "Website dedicated to MLB stats and analysis.",
  text2 = NULL
)


create_proj_card(
  img_src = "/Users/Stephan/Desktop/R Projects/personal-website/images/Dashboard (3).png",
  url = "https://public.tableau.com/app/profile/stephan.teodosescu/viz/NFLCharterFlights/Dashboard",
  title = "NFL Charter Flights",
  text = "Tableau: Dashboard exploring NFL team charter flight patterns. Created using Tableau Public.",
  text2 = NULL
)


create_proj_card(
  img_src = "images/sg_table.png",
  url = "https://steodosescu.quarto.pub/table-contest-2024/",
  title = "Table Contest 2024",
  text = "My submission for the Posit 2024 Table Contest.",
  text2 = NULL
)


create_proj_card(
  img_src = "images/streamlit-frame.png",
  url = "https://odds-converter.streamlit.app/",
  title = "Odds Converter Tool",
  text = "Web app allowing you to convert sports betting odds in different international systems and into implied probabilities.",
  text2 = NULL
)

create_proj_card(
  img_src = "images/NFL Grouped (2).png",
  url = "https://steodose.github.io/NFL/NFL-Summary-Report.html",
  title = "NFL Analytics",
  text = "Website dedicated to NFL advanced stats and analysis.",
  text2 = NULL
)

create_proj_card(
  img_src = "images/stocks.png",
  url = "https://steodosescu-stocks.streamlit.app/",
  title = "S&P 500 Stocks App",
  text = "Web app allowing you to retrieve stock price information for any company in the S&P 500 Index. Built using the Streamlit framework.",
  text2 = NULL
)

create_proj_card(
  img_src = "images/Big 5 Frame.png",
  url = "https://steodosescu.shinyapps.io/Big-5-Leagues/",
  title = "Big 5 Leagues Web App",
  text = "Dashboard looking at the current tables and statistics for the Big 5 European football leagues.",
  text2 = NULL
)


create_proj_card(
  img_src = "images/wordle-screenshot2.png",
  url = "https://steodosescu.shinyapps.io/Wordle/",
  title = "Wordle Web App",
  text = "Wordle site programmed using the Shiny web app framework. Inspired by Winston Chang's original app.",
  text2 = NULL
)


create_proj_card(
  img_src = "images/WP Dashboard Screenshot.png",
  url = "https://steodosescu.shinyapps.io/nfl-win-probability/",
  title = "NFL Win Probability Tool",
  text = "Dashboard that looks at individual NFL game win probability using data from the nflfastR package.",
  text2 = NULL
)



create_proj_card(
  img_src = "images/2022_FIFA_World_Cup.png",
  url = "https://steodosescu.shinyapps.io/World-Cup-Dashboard/",
  title = "2022 Men's FIFA World Cup Odds",
  text = "Dashboard highlighting win probabilities for each FIFA World Cup match, and overall team stats.",
  text2 = NULL
)



create_proj_card(
  img_src = "images/Home.png",
  url = "https://public.tableau.com/app/profile/stephan.teodosescu/viz/2021-22PremierLeague_16503505579010/Home
",
  title = "Tableau: World Football Matchday Portal",
  text = "A suite of dashboards highlighting standings and match outcomes of the biggest football leagues in the world. Built in Tableau Public.",
  text2 = NULL
)



create_proj_card(
  img_src = "images/PL.png",
  url = "https://steodosescu.shinyapps.io/club-soccer-forecasts/",
  title = "Club Soccer Forecasts",
  text = "My Club Soccer Forecasts app simulates and visualizes the results of the current Premier League season. Built using the Shiny app framework.",
  text2 = NULL
)




create_proj_card(
  img_src = "images/imdb-logo.png",
  url = "https://steodosescu.shinyapps.io/IMDB-Ratings-Tool/?_ga=2.10299253.1948351145.1648491200-1836928452.1639278433",
  title = "IMDB Ratings Tool",
  text = "TV series and ratings data for 1000+ shows in the IMDb database.",
  text2 = NULL
)




create_proj_card(
  img_src = "images/F1.png",
  url = "http://stephanteodosescu.com/F1/F1-Summary.html",
  title = "F1 Analytics",
  text = "Website dedicated to Formula 1 analytics and visualizaton.",
  text2 = NULL
)




create_proj_card(
  img_src = "images/US Air Travel.png",
  url = "https://public.tableau.com/app/profile/stephan.teodosescu/viz/U_S_AirTravel/USAirTravelDashboard",
  title = "Tableau: U.S. Air Travel Dashboard",
  text = "This dashboard explores how COVID-19 disrupted commericial airline travel in the United States. Created using Tableau Public.",
  text2 = NULL
)





```
